baseURL = 'https://nl-santhosh-kumar.github.io/terraform-associate-labs/'
languageCode = 'en-us'
title = 'Santhosh | Terraform Labs'
theme = 'PaperMod'
paginate = 5  # Shows 5 challenges per page

[params]
    env = 'production'
    title = "Terraform Associate Labs"
    description = "Documentation and insights from my HashiCorp certification journey."
    author = "Santhosh Kumar"
    
    # PaperMod specific UI
    defaultTheme = "dark" # Fits the "DevOps" aesthetic well
    ShowCodeCopyButtons = true
    mainSections = ["challenges", "posts"]
    showScrollToTop = true
    ShowSearchButton = true # Adds a magnifying glass to the menu

    [params.homeInfoParams]
        Title = "Terraform Lab Notes \U0001F4BB"
        Content = "Hands-on labs for the Terraform Associate Certification. Covering Providers, State, Modules, and AWS integration."
    [params.profileMode]
        enabled = true
        title = "Santhosh Kumar"
        subtitle = " DevOps Engineer | Terraform Associate Candidate"
        [[params.profileMode.buttons]]
            name = "View Challenges"
            url = "/challenges"
        [[params.profileMode.buttons]]
            name = "GitHub Profile"
            url = "https://github.com/nl-santhosh-kumar"

    [params.editPost]
        URL = "https://github.com/nl-santhosh-kumar/terraform-associate-labs/tree/main/portfolio/content"
        Text = "View Post Source"
        appendFilePath = true # This automatically adds /posts/challenge-01.md to the URL
    
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/nl-santhosh-kumar/terraform-associate-labs"
    
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/santhosh-kumar-r-04711024/"

[menu]
    [[menu.main]]
        identifier = "search"
        name = "Search"
        url = "/search/"
        weight = 1

[security]
  [security.funcs]
    getenv = ['^HUGO_']
  [security.http]
    methods = ['(?i)GET|POST']
  [security.path]
    allow = ['..'] # This allows Hugo to read your lab folders

[taxonomies]
    category = "categories"
    series = "series" # This allows you to group labs as "Terraform Associate Series"
    tag = "tags"

[outputs]
    home = ["HTML", "RSS", "JSON"] # This generates the search index