name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"] # Ensure this matches your default branch name
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash
    working-directory: ./portfolio # Change this if your Hugo folder is named differently
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # NEW: Setup Go (Required for Hugo Modules)
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      # NEW: Fetch Hugo Modules
      - name: Install dependencies
        run: |
          hugo mod get -u
          hugo mod tidy
        working-directory: ./portfolio

      - name: Build with Hugo
        run: |
          hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
        working-directory: ./portfolio # Tells Hugo where the config file is

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./portfolio/public